name: Build, Test & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RUST_VERSION: 1.58

jobs:
  accept:
    name: Accept
    runs-on: ubuntu-latest
    needs: [build_and_push]
    steps:
      - name: Accept
        run: true

  build_and_push:
    name: Build image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # linux/arm64 is disabled for now pending native runners; building in
        # qemu-aarch64 is too slow and costly.
        # See <https://github.com/actions/virtual-environments/issues/2187>
        host: [linux/amd64] # linux/arm64
        target: [x86_64, aarch64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ matrix.platform }}
          build-args: TARGET=${{ matrix.target }}
          tags: ghcr.io/${{ github.repository }}:${{ env.RUST_VERSION }}-${{ matrix.target }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Test image
        run:
          docker run --pull always --platform ${{ matrix.platform }} --rm ghcr.io/${{ github.repository }}:${{ env.RUST_VERSION }}-${{ matrix.target }} rustc --version
